version: '3.9'

service:
  postgres:
    image: postgres:16
    environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgrespass
    POSTGRES_DB: cryptocoins
  volumes:
    - .deployment/migrations/postgres:/docker-entrypoint-initdb.POSTGRES_DB
  ports:
    - "5432:5432"
